sudo: required
dist: trusty

compiler:
    - clang

git:
    submodules: false

before_install:
    - git submodule update --init --recursive
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang-3.7 cmake

env:
    global:
        - CXX=clang++-3.7
        - CC=clang-3.7

before_script:
    - mkdir build
    - cd build

script:
    - cmake ../
    - make
    - ./tests/bedrockTests