sudo: false

compiler:
    - clang

git:
    submodules: false

before_install:
    - git submodule update --init --recursive

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

env:
    global:
        - CXX=clang++-3.7
        - CC=clang-3.7

before_script:
    - mkdir build
    - cd build

script:
    - cmake ../
    - make
    - ./tests/bedrockTests