sudo: false

compiler:
    - clang

git:
    submodules: false

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
        packages:
            - cmake
            - clang-3.6

before_install:
    - git submodule update --init --recursive

env:
    global:
        - CXX=clang++-3.6
        - CC=clang-3.6

script:
    - mkdir build
    - cd build
    - cmake ../
    - make
    - ./tests/bedrockTests