sudo: required
dist: trusty

compiler:
    - clang

git:
    submodules: false

before_install:
    - git submodule update --init --recursive
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq clang-3.6 cmake gcc-4.9

env:
    global:
        - CXX=clang++-3.6
        - CC=clang-3.6

before_script:
    - mkdir build
    - cd build

script:
    - cmake ../
    - make
    - ./tests/bedrockTests